Keepa/config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root to: 'pages#index'

  get 'pages/index'

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new, :destroy]

  delete '/logout', to: 'sessions#destroy', as: :logout
end

Keepa/app/models/user.rb
# user used to be in use
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
end

Keepa/app/controllers/application_controller.rb
# bla bla bla
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    id = session[:user_id]
    @current_user ||= User.find(id) if id
  end
end

Keepa/app/controllers/sessions_controller.rb
# la la la
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      flash[:warning] = 'You are wrong'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'See you soon!'
    redirect_to root_path
  end
end

Keepa/app/controllers/users_controller.rb
# some funny comment
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User was successfully created'
      redirect_to root_path
    else
      render :new
    end
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

Keepa/app/helpers/sessions_helper.rb
module SessionsHelper
end

Keepa/app/helpers/users_helper.rb
# help
module UsersHelper
end

Keepa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keepa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Keepa/app/views/pages/index.html.erb
<% if current_user %>
  You are logged in as <%= current_user.email %>
  <%= link_to 'Log out', logout_path, method: :delete  %>
<% else %>
  <%= link_to 'Log in', new_session_path %>
  <%= link_to 'Register', new_user_path %>
<% end %>

Keepa/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div>
    <h5>Some errors were found</h5>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message.to_s %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Keepa/app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

Keepa/app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>